[supervisord]
nodaemon=true
user=root
loglevel=info
logfile=/logs/supervisord.log
logfile_maxbytes=5MB
logfile_backups=3

[program:web]
command=gunicorn --bind 0.0.0.0:8080 --workers 2 --timeout 30 --access-logfile /logs/gunicorn-access.log --error-logfile /logs/gunicorn-error.log app.web:app
directory=/opt/mail-gateway
environment=MSMTPQ_Q="/var/spool/msmtp",PYTHONPATH="/opt/mail-gateway"
autorestart=true
startretries=5
stdout_logfile=/logs/web.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile=/logs/web.err
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=2

[program:scheduler]
command=python3 /opt/mail-gateway/app/scheduler.py
directory=/opt/mail-gateway
user=mail
environment=MSMTPQ_Q="/var/spool/msmtp",PYTHONPATH="/opt/mail-gateway"
autorestart=true
startretries=5
stdout_logfile=/logs/scheduler.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile=/logs/scheduler.err
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=2