[global]
nice = -1

[webif]
httpport        = 8888
httpuser        = admin
httppwd         = deinpasswort
httpallowed     = 0.0.0.0-255.255.255.255

[dvbapi]
enabled        = 1
au             = 1
boxtype        = pc
user           = dvbapi
pmt_mode       = 4
request_mode   = 1
listen_port    = 9000
