#!/usr/bin/env python3
"""
Configuration generator for Mail Gateway.

Reads /config/config.yaml and /config/accounts.yaml and generates:
  - /etc/msmtprc          (msmtp config)
  - /runtime/getmail/<name>.conf  (one file per account)

These files must never be edited manually – they are overwritten on every start
and whenever /api/reload is called.
"""

from __future__ import annotations

import logging
import os
import stat
from pathlib import Path

import yaml

# ── Paths ─────────────────────────────────────────────────────────────────────

CONFIG_FILE = Path("/config/config.yaml")
ACCOUNTS_FILE = Path("/config/accounts.yaml")
RUNTIME_DIR = Path("/runtime")
GETMAIL_DIR = RUNTIME_DIR / "getmail"
MSMTPRC = Path("/etc/msmtprc")
MSMTPQ_BIN = Path("/usr/libexec/msmtp/msmtpq/msmtpq")

# ── Logging ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
log = logging.getLogger("generator")


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_yaml(path: Path) -> dict:
    """Load a YAML file and return a dict (empty dict on empty file)."""
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def ensure_directories() -> None:
    """Create all runtime directories expected by the container."""
    for d in [
        GETMAIL_DIR,
        RUNTIME_DIR / "status",
        Path("/logs"),
        Path("/var/spool/msmtp"),
    ]:
        d.mkdir(parents=True, exist_ok=True)
        log.debug("Directory ready: %s", d)


# ── msmtprc ───────────────────────────────────────────────────────────────────

def write_msmtprc(config: dict) -> None:
    """Generate /etc/msmtprc from the smtp section of config.yaml."""
    smtp = config["smtp"]

    tls_on = smtp.get("tls", False)
    tls_line = "tls on\ntls_trust_file /etc/ssl/certs/ca-certificates.crt" if tls_on else "tls off"

    auth_lines = ""
    if smtp.get("username"):
        auth_lines = (
            f"\nauth on"
            f"\nuser {smtp['username']}"
            f"\npassword {smtp['password']}"
        )
    else:
        auth_lines = "\nauth off"

    from_addr = smtp.get("from", "postmaster@localhost")

    content = f"""# Generated by mail-gateway – do NOT edit manually
# Changes will be overwritten on next start or config reload.

defaults
{tls_line}
logfile /logs/msmtp.log

account default
host {smtp['host']}
port {smtp['port']}
{tls_line}{auth_lines}
from {from_addr}
"""

    MSMTPRC.write_text(content, encoding="utf-8")
    MSMTPRC.chmod(stat.S_IRUSR | stat.S_IWUSR)
    log.info("Written %s", MSMTPRC)


# ── getmail configs ───────────────────────────────────────────────────────────

_RETRIEVER_TYPES: dict[str, str] = {
    "pop3":  "BrokenUIDLPOP3Retriever",
    "pop3s": "BrokenUIDLPOP3SSLRetriever",
    "imap":  "SimpleIMAPRetriever",
    "imaps": "SimpleIMAPSSLRetriever",
}


def _retriever_type(protocol: str) -> str:
    key = protocol.lower()
    if key not in _RETRIEVER_TYPES:
        raise ValueError(f"Unsupported protocol: {protocol!r}")
    return _RETRIEVER_TYPES[key]


def write_getmail_conf(account: dict) -> None:
    """Generate /runtime/getmail/<name>.conf for a single mail account."""
    name = account["name"]
    protocol = account["protocol"].lower()
    retriever = _retriever_type(protocol)

    # IMAP accounts can specify additional mailboxes.
    # Always use trailing comma so a single entry is also a valid Python tuple.
    mailboxes_line = ""
    if protocol.startswith("imap"):
        mboxes = account.get("mailboxes", ["INBOX"])
        items = ", ".join(f'"{m}"' for m in mboxes)
        mailboxes_line = f"\nmailboxes = ({items},)"

    deliver_to = account.get("deliver_to", account["username"])
    delete = str(account.get("delete", False)).lower()
    read_all = str(account.get("read_all", True)).lower()

    # State directory for getmail (UIDs etc.)
    state_dir = GETMAIL_DIR / name
    state_dir.mkdir(parents=True, exist_ok=True)

    conf = f"""# Generated by mail-gateway – do NOT edit manually
# Account: {name}

[retriever]
type = {retriever}
server = {account['host']}
port = {account['port']}
username = {account['username']}
password = {account['password']}{mailboxes_line}

[destination]
type = MDA_external
path = {MSMTPQ_BIN}
arguments = ("-f", "%(sender)", "--", "{deliver_to}")

[options]
read_all = {read_all}
delete = {delete}
allow_mda_root = true
message_log = /logs/getmail-{name}.log
message_log_syslog = false
"""

    conf_path = GETMAIL_DIR / f"{name}.conf"
    conf_path.write_text(conf, encoding="utf-8")
    conf_path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    log.info("Written %s", conf_path)


# ── Main entry ────────────────────────────────────────────────────────────────

def generate() -> None:
    """Generate all runtime configuration files."""
    config = load_yaml(CONFIG_FILE)
    accounts_data = load_yaml(ACCOUNTS_FILE)
    accounts: list[dict] = accounts_data.get("accounts", [])

    ensure_directories()
    write_msmtprc(config)

    # Remove stale account configs before re-generating
    for old_conf in GETMAIL_DIR.glob("*.conf"):
        old_conf.unlink()

    for account in accounts:
        write_getmail_conf(account)

    log.info("Configuration generated for %d account(s).", len(accounts))


if __name__ == "__main__":
    generate()